# Generated by Django 5.1.1 on 2024-10-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servicesenquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicetype', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('ServiceDescription', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
