# Generated by Django 5.1.1 on 2024-10-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesenquiry',
            old_name='ServiceDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='servicesenquiry',
            old_name='category',
            new_name='service_category',
        ),
        migrations.RenameField(
            model_name='servicesenquiry',
            old_name='servicetype',
            new_name='service_type',
        ),
    ]
