# Generated by Django 5.1.1 on 2024-10-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0006_notification_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
