# Generated by Django 5.1.1 on 2024-10-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='category',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
