# Generated by Django 5.1.1 on 2024-10-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0009_forum_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servicesenquiry',
            new_name='Services',
        ),
    ]
