# Generated by Django 5.1.1 on 2024-10-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0019_rsvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
    ]
