# Generated by Django 5.1.1 on 2024-10-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0020_remove_forum_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='contact_info',
        ),
    ]
