# Generated by Django 5.1.1 on 2024-10-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0021_remove_ad_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='contact_info',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
