# Generated by Django 5.1.1 on 2024-10-21 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0023_remove_ad_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='service',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='society.forum'),
            preserve_default=False,
        ),
    ]
