# Generated by Django 5.1.1 on 2024-10-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0025_remove_comment_post_comment_service_comments_replys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replys',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replys',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Replys',
        ),
    ]
