# Generated by Django 5.1.1 on 2024-10-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0029_room_roommessage_delete_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_urgent',
        ),
    ]
