# Generated by Django 5.1.1 on 2024-10-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0030_remove_notification_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
