# Generated by Django 5.1.1 on 2024-10-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0031_notification_is_urgent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_id', models.CharField(max_length=255, unique=True)),
                ('download_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
