# Generated by Django 5.1.1 on 2024-10-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0032_drivefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivefile',
            name='uploaded_at',
        ),
    ]
