# Generated by Django 5.1.1 on 2024-11-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0034_location_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
