# Generated by Django 5.1.1 on 2024-11-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0035_alter_event_location_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='predefined_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
