# Generated by Django 5.1.1 on 2024-11-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0037_alter_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='predefined_location',
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
